### ISSUE TITLE
Ambiguity in extension scaffold README

### ISSUE THREAD

**Issue by geraldus** [lambdacms/lambdacms#11]
> ``` bash
> export TMP_CLONE=/tmp/lambdacms-clone-for-extension-scaffolding-`date +%s`
> git clone --depth=1 https://github.com/lambdacms/lambdacms.git $TMP_CLONE
> cp -r $TMP_CLONE/scaffold-extension .
> rm -rf $TMP_CLONE
> cd scaffold-extension
> ```
> 
> Here we clone it into the `mysite-post` folder, hinting that we will
> create a `testimonial` extension to a base app called `mysite`.

I guess, this should be:

``` bash
mkdir mysite-post
cd mysite-post
export TMP_CLONE=/tmp/lambdacms-clone-for-extension-scaffolding-`date +%s`
git clone --depth=1 https://github.com/lambdacms/lambdacms.git $TMP_CLONE
cp -r $TMP_CLONE/scaffold-extension/* .
rm -rf $TMP_CLONE
```

**Comment by cies** [comment]
Yes this is not correct. I hope I fixed it now. Please close if you consider the fix appropriate.
