### ISSUE TITLE
Extension scaffold issues

### ISSUE THREAD

**Issue by geraldus** [lambdacms/lambdacms#13]
I have found few minor issues with extension scaffold.

Look,

```
englishMessage Menu%MODEL%            = "%LCS_MODEL%s"
englishMessage %MODEL%Index           = "%LCS_MODEL% overview"
englishMessage New%MODEL%             = "New %LCS_MODEL%"
englishMessage Edit%MODEL%            = "Edit %LCS_MODEL%"
```

After running boot script it is converted to something like this:

```
englishMessage MenuPets            = " pets"
englishMessage PetsIndex           = " pets overview"
englishMessage NewPets             = "New  pets"
englishMessage EditPets            = "Edit  pets"
```

and etc., notice leading whitespace in first two messages and double whitespace in other messages.

**Comment by geraldus** [comment]
Also, this<sup>[1]</sup> code could be simplified
```hs
import           %PACKAGE%.%MODEL%.Message (%MODEL%Message, defaultMessage, englishMessage)
import qualified %PACKAGE%.%MODEL%.Message as Msg
```
to
```hs
import           %PACKAGE%.%MODEL%.Message (%MODEL%Message, defaultMessage, englishMessage) as Msg
```


[1]:https://github.com/lambdacms/lambdacms/blob/master/scaffold-extension/PACKAGE/MODEL/Foundation.hs#L20-L21

**Comment by cies** [comment]
Hmm. That's wrong indeed.

**Comment by cies** [comment]
I found the issue, it is in this line of `create_extension_scaffold.sh`:

```
lcs_model=$(echo "$model" | sed 's/\([A-Z][^A-Z]\)/ \1/g' | tr '[:upper:]' '[:lower:]')
```

It adds spaces before each bit of a CamelCaseWord (so it becomes " camel case word").

**Comment by geraldus** [comment]
Thanks!
