### ISSUE TITLE
Export default admin and admin-auth layout functions

### ISSUE THREAD

**Issue by geraldus** [lambdacms/lambdacms#15]
Currently default `adminLayout` and `adminAuthLayout` implementations are inlined in `LambdaCms` class definition.  This does not allow to override them easily: (I believe in most cases) all default implementation should be copied among with default templates.  Would it make sense to move default implementations to top level and exporting them?  E.g.

``` hs
class ( … ) => LambdaCmsAdmin master where
  …
  adminLayout :: WidgetT master IO () -> HandlerT master IO Html
  adminLayout widget = defaultAdminLayout

  adminAuthLayout :: WidgetT master IO () -> HandlerT master IO Html
  adminAuthLayout widget = defaultAdminAuthLayout
  …

defaultAdminLayout :: (…) => WidgetT master IO () -> HandlerT master IO Html
defaultAdminLayout = …

defaultAdminAuthLayout :: (…) => WidgetT master IO () -> HandlerT master IO Html
defaultAdminAuthLayout = …
```

In my case I'm using Summernote editor and it requires some scripts and links to be injected in page's `<head>`, so I have to do it in each handler function where I need Summernote (for all request methods).  I'd better to override default admin layout in LambdaCms class instance definition of my app:

``` hs
instance LambdaCmsAdmin App where
  …
  authLayout widget = defaultAuthLayout $ includeSummernote >> widget
```

this will eliminate me from ubiquitous `icludeSummernote` in my handlers, moreover if for some reason I will decide not to inject Summernote dependencies in some handlers I will have a cheap way — `defaultAdminLayout`.

I would be glad to send a pull request for these changes if you'll agree.

**Comment by cies** [comment]
I like the proposal. Go ahead with the PR.
