### ISSUE TITLE
Password reset handler stores passwords insecure

### ISSUE THREAD

**Issue by geraldus** [lambdacms/lambdacms#16]
Current implementation of password reset handler saves password given by user unmodified, that is insecure<sup>[[1](https://github.com/lambdacms/lambdacms/blob/master/lambdacms-core/LambdaCms/Core/Handler/User.hs#L274-L282)]</sup>.  Also this is an issue when using `Yesod.Auth.Email` plugin because it expects password to be a salted hash generated with `saltPass`<sup>[[2](https://github.com/yesodweb/yesod/blob/master/yesod-auth/Yesod/Auth/Email.hs#L571)]</sup>.  Initially I thought about some password transformation function in LambdaCms class, but then realized that Email plugin seems to be the only one plugin which stores passwords, other plugins imply external password storage.  And I have no strong opinion about situation when Email plugin will be used with other hypothetic plugin which stores passwords differently, looks like then it will be a mess.  Should we simply default to fact that password should be hashed for now and save hashed passwords?

**Comment by cies** [comment]
I do not understand the issue fully. But I'm very much willing to accept you PR. In LambdaCms' current state it is important to have some features working in order to move forward. In this light I'm very relax w.r.t. PRs that may not be the "best possible", as long as they fix issues at hand.

**Comment by geraldus** [comment]
@cies well, `Yesod.Auth.Email` allows to override password getter, but storing naked password is issue anyway.  `lambdacms-core` have `yesod-auth` as dependency already, so I guess it's OK if we use `saltPass` from `Yesod.Auth.Email`.

**Comment by cies** [comment]
Sure that's fine. Re-use where possible.
