### ISSUE TITLE
Links are incorrect at lambdacms.org and old repo

### ISSUE THREAD

**Issue by Tehnix** [lambdacms/lambdacms#3]
The watch and fork on [http://lambdacms.org](http://lambdacms.org) is pointing to the old repository at [https://github.com/lambdacms/lambdacms-core/](https://github.com/lambdacms/lambdacms-core/).

Also, the README text on [https://github.com/lambdacms/lambdacms-core/](https://github.com/lambdacms/lambdacms-core/) is incorrectly pointing to [https://github.org/lambdacms/lambdacms](https://github.org/lambdacms/lambdacms) (notice the .org, where it should be .com).

**Comment by cies** [comment]
Thanks!  Due to some issue the watch and fork buttons were not even working anymore. Thanks @matsrietdijk for fixing that.

As for the README, this repo is depricated and will be removed soon.

Thanks for reporting, sorry for the late reply.
