### ISSUE TITLE
Manual patching instructions issues

### ISSUE THREAD

**Issue by geraldus** [lambdacms/lambdacms#5]
Hi folks!  I'm really excited about LambdaCms!  I hope it will fit my current needs.
I'm updating one my existing project to use LambdaCms right now, so I decided to go manual patching way.

This is from instructions [[1](https://github.com/lambdacms/lambdacms-core/wiki/Getting-Started-Manually#modify-the-configmodels-file)]:

> #### Modify the `config/models` file
> 
> Replace **all** of the file's content with the following `UserRole` definition:
> 
> ```
> UserRole
>     userId UserId
>     roleName RoleName
>     UniqueUserRole userId roleName
>     deriving Typeable Show
> ```

and then there are instructions how to update **Application.hs**, where new user creation occurs in `makeFoundation` function:

> ``` haskell
>     madmin <- runSqlPool (getBy (UniqueEmail admin)) pool
>     case madmin of
>         Nothing -> do
>             timeNow <- getCurrentTime
>             uuid <- generateUUID
>             flip runSqlPool pool $ do
>                 uid <- insert User { userIdent     = uuid
>                                    , userPassword  = Nothing
>                                    , userName      = takeWhile (/= '@') admin
>                                    , userEmail     = admin
>                                    , userActive    = True
>                                    , userToken     = Nothing
>                                    , userCreatedAt = timeNow
>                                    , userLastLogin = Nothing
>                                    , userDeletedAt = Nothing
>                                    }
> ```

However, if we replaced all contents in `config/models` there is no `User` data type, isn't?  So, I guess there should be `User` model described it that section also.

Regards.

**Comment by cies** [comment]
Hi Артур! (leaning Bulgarian at the moment, so using this opportunity to type some Cyrillic)

The User is defined here: https://github.com/lambdacms/lambdacms/blob/master/lambdacms-core/config/models

You are also adding the dependency on lambdacms-core at some point, and from there you get the user model. It could be clearer from the documentation.

Please note that you are using the `lamdacms-core` repo, which is deprecated! This because we moves to a "mega repo" structure. See the notice that the top of the Github page. This is the repo (and the README) that you should be working from: https://github.com/lambdacms/lambdacms

Sorry for the confusion, I'll remove these deprecated repo's soon.

**Comment by geraldus** [comment]
> The User is defined here: https://github.com/lambdacms/lambdacms/blob/master/lambdacms-core/config/models

Oh, got it, I haven't a chance to look at sources yet.  But I definitely will and very likely will contribute in some way (missing CMS features in Yesod was the only reason why I still writing php code! And in fact I thought about implementing Yesod admin interface myself, I was very excited and surprised when discovered  LambdaCms!)

> Please note that you are using the lamdacms-core repo

This is because I didn't find manual patching guide in mega-repo.

**Comment by geraldus** [comment]
So, I'll close this.

**Comment by geraldus** [comment]
Oh, by the way

> By default the application uses Mozilla's Persona to log in

Have received email from Mozilla?  They're deprecating Persona :(

**Comment by geraldus** [comment]
Also, looking at patches now and it looks like https://github.com/lambdacms/lambdacms-core/wiki/Getting-Started-Manually#modify-the-configmodels-file is a bit outdated (so do https://github.com/lambdacms/lambdacms/blob/master/docs/role-based-authorization.md)

I will try to follow patches and when I'll make my website working with LambdaCms I could try to update docs.

**Comment by cies** [comment]
> They're deprecating Persona :(

Yeah. I'm reluctant to make a quick move as the announcement is still so fresh that I consider it possible for some organisation to take the service over from Mozilla.

> I will try to follow patches and when I'll make my website working with LambdaCms I could try to update docs.

That's really great. I'd love to see some more action around this project. :)

While the feature set of this project is currently quite minimal, it does provide a strong basis to make further improvements. You will end up with a very modular code base when using LambdaCms, and you can easily contribute extensions (providing some functionality) back to the community.

Needless to say this thing is FAAAAST and über-type-safe, like Yesod!

**Comment by geraldus** [comment]
@cies how can I chat with you of other active maintainers (e.g. IRC, G+, etc.)?

**Comment by geraldus** [comment]
@cies ok, I updated my site and now admin interface works.  However, it shows me only `Users` section, how to make other models from my app's `config/models` to be shown in admin menu (it is supposed to be automated)?

**Comment by cies** [comment]
I'm on Freenode (IRC) #lambdacms this morning (CET).

Good to hear you are having some success. All other models you want in the admin section you will want to make "extensions" for pretty much each of the (this ensures modularity).

Here the docs for setting up a new extension: https://github.com/lambdacms/lambdacms/tree/master/scaffold-extension

In those docs you find how to wire the new extension into your "base" application pointed by a link, please do not over look it (it is an important part). I supply it here too (it currently points to the docs for wireing up the `lambdacms-media` extension, as it is the same as wireing up any other extension): https://github.com/lambdacms/lambdacms/tree/master/lambdacms-media

Good luck! It really should not be too hard.

The benefit of putting everything in extensions is huge: extensions are just Yesod subsites thar require `lambdacms-core`, but they use cabal's dependency mechanism to depend on eachother. This way some extension can enforce dependencies on other extensions. Once you have an extension that you wish to use in another project, you simply do so as it is already a "package".

**Comment by geraldus** [comment]
@cies ping, missing you on IRC, I've sent you a request in Google Hangouts, have few questions.
